### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by adkron** [aslakhellesoy/ansicolor#1]
Can you get a compiled version up somewhere?  Or maybe place this gem on gemcutter?

**Comment by aslakhellesoy** [comment]
I'm not planning on working more on this. I recommend http://github.com/aslakhellesoy/wac instead. If you want this is for Cucumber on JRuby on Windows, I'm planning on integrating http://jansi.fusesource.org/ instead, which is essentially a better implementation than my ansicolor project.
